name: PythonCI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # we want to test our package on several versions of Python
        python-version: [^3.10]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        # make depends on poetry
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          make install
      - name: Run linter and pytest
        env: 
          DEBUG: 1
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: |
          make lint
          make test
      - name: Make coverage .xml
        run:
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=fomineandrrei_python-project-52
            -Dsonar.organization=fomineandrei
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.coverage.exclusions=tests/**
            -Dsonar.exclusions=tests/**